// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type RideStatus string

const (
	RideStatusREQUESTED  RideStatus = "REQUESTED"
	RideStatusACCEPTED   RideStatus = "ACCEPTED"
	RideStatusINPROGRESS RideStatus = "IN_PROGRESS"
	RideStatusCOMPLETED  RideStatus = "COMPLETED"
	RideStatusCANCELLED  RideStatus = "CANCELLED"
)

func (e *RideStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RideStatus(s)
	case string:
		*e = RideStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RideStatus: %T", src)
	}
	return nil
}

type NullRideStatus struct {
	RideStatus RideStatus `json:"ride_status"`
	Valid      bool       `json:"valid"` // Valid is true if RideStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRideStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RideStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RideStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRideStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RideStatus), nil
}

type TOutboxEvent struct {
	EventID            pgtype.UUID        `json:"event_id"`
	EventAggregateID   string             `json:"event_aggregate_id"`
	EventAggregateType string             `json:"event_aggregate_type"`
	EventType          string             `json:"event_type"`
	EventPayload       []byte             `json:"event_payload"`
	EventStatus        string             `json:"event_status"`
	EventCreatedAt     pgtype.Timestamptz `json:"event_created_at"`
	EventUpdatedAt     pgtype.Timestamptz `json:"event_updated_at"`
	EventPublishedAt   pgtype.Timestamptz `json:"event_published_at"`
}

type TRide struct {
	RideID         pgtype.UUID        `json:"ride_id"`
	RideRiderID    pgtype.UUID        `json:"ride_rider_id"`
	RideDriverID   pgtype.UUID        `json:"ride_driver_id"`
	RidePickupLat  pgtype.Numeric     `json:"ride_pickup_lat"`
	RidePickupLon  pgtype.Numeric     `json:"ride_pickup_lon"`
	RideDropoffLat pgtype.Numeric     `json:"ride_dropoff_lat"`
	RideDropoffLon pgtype.Numeric     `json:"ride_dropoff_lon"`
	RideStatus     RideStatus         `json:"ride_status"`
	RidePrice      pgtype.Numeric     `json:"ride_price"`
	RideCreatedAt  pgtype.Timestamptz `json:"ride_created_at"`
	RideUpdatedAt  pgtype.Timestamptz `json:"ride_updated_at"`
}
