// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptRide(ctx context.Context, arg AcceptRideParams) (TRide, error)
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (TOutboxEvent, error)
	CreateRide(ctx context.Context, arg CreateRideParams) (TRide, error)
	GetPendingOutboxEvents(ctx context.Context, limit int32) ([]TOutboxEvent, error)
	GetRideByID(ctx context.Context, rideID pgtype.UUID) (TRide, error)
	// sqlc.nargs allows to pass optional parameters to the query. If the parameter is not provided, it will be NULL, and the condition will be ignored.
	ListRides(ctx context.Context, arg ListRidesParams) ([]TRide, error)
	MarkOutboxEventAsFailed(ctx context.Context, eventID pgtype.UUID) error
	MarkOutboxEventAsPublished(ctx context.Context, eventID pgtype.UUID) error
	// -- name: AcceptRide :one
	// UPDATE t_rides
	// SET ride_status = 'ACCEPTED', ride_driver_id = $2, ride_updated_at = NOW()
	// WHERE ride_id = $1 AND ride_status = 'REQUESTED'
	// RETURNING *;
	UpdateRideStatus(ctx context.Context, arg UpdateRideStatusParams) (TRide, error)
	UpdateTripStatus(ctx context.Context, arg UpdateTripStatusParams) (TRide, error)
}

var _ Querier = (*Queries)(nil)
