// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptRide(ctx context.Context, arg AcceptRideParams) (TRide, error)
	CreateRide(ctx context.Context, arg CreateRideParams) (TRide, error)
	GetRideByID(ctx context.Context, rideID pgtype.UUID) (TRide, error)
	// sqlc.nargs allows to pass optional parameters to the query. If the parameter is not provided, it will be NULL, and the condition will be ignored.
	ListRides(ctx context.Context, arg ListRidesParams) ([]TRide, error)
	UpdateRideStatus(ctx context.Context, arg UpdateRideStatusParams) (TRide, error)
}

var _ Querier = (*Queries)(nil)
