// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ride.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptRide = `-- name: AcceptRide :one
UPDATE t_rides
SET ride_status = 'ACCEPTED'::ride_status,
    ride_driver_id = $1,
    ride_updated_at = NOW()
WHERE ride_id = $2
  AND ride_status = 'REQUESTED'::ride_status
RETURNING ride_id, ride_rider_id, ride_driver_id, ride_pickup_lat, ride_pickup_lon, ride_dropoff_lat, ride_dropoff_lon, ride_status, ride_price, ride_created_at, ride_updated_at
`

type AcceptRideParams struct {
	RideDriverID pgtype.UUID `json:"ride_driver_id"`
	RideID       pgtype.UUID `json:"ride_id"`
}

func (q *Queries) AcceptRide(ctx context.Context, arg AcceptRideParams) (TRide, error) {
	row := q.db.QueryRow(ctx, acceptRide, arg.RideDriverID, arg.RideID)
	var i TRide
	err := row.Scan(
		&i.RideID,
		&i.RideRiderID,
		&i.RideDriverID,
		&i.RidePickupLat,
		&i.RidePickupLon,
		&i.RideDropoffLat,
		&i.RideDropoffLon,
		&i.RideStatus,
		&i.RidePrice,
		&i.RideCreatedAt,
		&i.RideUpdatedAt,
	)
	return i, err
}

const createRide = `-- name: CreateRide :one
INSERT INTO
    t_rides (
    ride_rider_id,
    ride_pickup_lat,
    ride_pickup_lon,
    ride_dropoff_lat,
    ride_dropoff_lon,
    ride_price
)
VALUES
    ($1, $2, $3, $4, $5, $6)
    RETURNING
  ride_id, ride_rider_id, ride_driver_id, ride_pickup_lat, ride_pickup_lon, ride_dropoff_lat, ride_dropoff_lon, ride_status, ride_price, ride_created_at, ride_updated_at
`

type CreateRideParams struct {
	RideRiderID    pgtype.UUID    `json:"ride_rider_id"`
	RidePickupLat  pgtype.Numeric `json:"ride_pickup_lat"`
	RidePickupLon  pgtype.Numeric `json:"ride_pickup_lon"`
	RideDropoffLat pgtype.Numeric `json:"ride_dropoff_lat"`
	RideDropoffLon pgtype.Numeric `json:"ride_dropoff_lon"`
	RidePrice      pgtype.Numeric `json:"ride_price"`
}

func (q *Queries) CreateRide(ctx context.Context, arg CreateRideParams) (TRide, error) {
	row := q.db.QueryRow(ctx, createRide,
		arg.RideRiderID,
		arg.RidePickupLat,
		arg.RidePickupLon,
		arg.RideDropoffLat,
		arg.RideDropoffLon,
		arg.RidePrice,
	)
	var i TRide
	err := row.Scan(
		&i.RideID,
		&i.RideRiderID,
		&i.RideDriverID,
		&i.RidePickupLat,
		&i.RidePickupLon,
		&i.RideDropoffLat,
		&i.RideDropoffLon,
		&i.RideStatus,
		&i.RidePrice,
		&i.RideCreatedAt,
		&i.RideUpdatedAt,
	)
	return i, err
}

const getRideByID = `-- name: GetRideByID :one
SELECT
    ride_id, ride_rider_id, ride_driver_id, ride_pickup_lat, ride_pickup_lon, ride_dropoff_lat, ride_dropoff_lon, ride_status, ride_price, ride_created_at, ride_updated_at
FROM
    t_rides
WHERE
    ride_id = $1
    LIMIT
  1
`

func (q *Queries) GetRideByID(ctx context.Context, rideID pgtype.UUID) (TRide, error) {
	row := q.db.QueryRow(ctx, getRideByID, rideID)
	var i TRide
	err := row.Scan(
		&i.RideID,
		&i.RideRiderID,
		&i.RideDriverID,
		&i.RidePickupLat,
		&i.RidePickupLon,
		&i.RideDropoffLat,
		&i.RideDropoffLon,
		&i.RideStatus,
		&i.RidePrice,
		&i.RideCreatedAt,
		&i.RideUpdatedAt,
	)
	return i, err
}

const listRides = `-- name: ListRides :many
SELECT ride_id, ride_rider_id, ride_driver_id, ride_pickup_lat, ride_pickup_lon, ride_dropoff_lat, ride_dropoff_lon, ride_status, ride_price, ride_created_at, ride_updated_at FROM t_rides
WHERE (ride_rider_id = $3 OR $3 IS NULL)
    AND (ride_driver_id = $4 OR $4 IS NULL)
    AND (ride_status = $5 OR $5 IS NULL)
ORDER BY ride_created_at DESC
LIMIT $1 OFFSET $2
`

type ListRidesParams struct {
	Limit    int32          `json:"limit"`
	Offset   int32          `json:"offset"`
	RiderID  pgtype.UUID    `json:"rider_id"`
	DriverID pgtype.UUID    `json:"driver_id"`
	Status   NullRideStatus `json:"status"`
}

// sqlc.nargs allows to pass optional parameters to the query. If the parameter is not provided, it will be NULL, and the condition will be ignored.
func (q *Queries) ListRides(ctx context.Context, arg ListRidesParams) ([]TRide, error) {
	rows, err := q.db.Query(ctx, listRides,
		arg.Limit,
		arg.Offset,
		arg.RiderID,
		arg.DriverID,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TRide
	for rows.Next() {
		var i TRide
		if err := rows.Scan(
			&i.RideID,
			&i.RideRiderID,
			&i.RideDriverID,
			&i.RidePickupLat,
			&i.RidePickupLon,
			&i.RideDropoffLat,
			&i.RideDropoffLon,
			&i.RideStatus,
			&i.RidePrice,
			&i.RideCreatedAt,
			&i.RideUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRideStatus = `-- name: UpdateRideStatus :one

UPDATE t_rides
SET ride_status = $2, ride_updated_at = NOW()
WHERE ride_id = $1
RETURNING ride_id, ride_rider_id, ride_driver_id, ride_pickup_lat, ride_pickup_lon, ride_dropoff_lat, ride_dropoff_lon, ride_status, ride_price, ride_created_at, ride_updated_at
`

type UpdateRideStatusParams struct {
	RideID     pgtype.UUID `json:"ride_id"`
	RideStatus RideStatus  `json:"ride_status"`
}

// -- name: AcceptRide :one
// UPDATE t_rides
// SET ride_status = 'ACCEPTED', ride_driver_id = $2, ride_updated_at = NOW()
// WHERE ride_id = $1 AND ride_status = 'REQUESTED'
// RETURNING *;
func (q *Queries) UpdateRideStatus(ctx context.Context, arg UpdateRideStatusParams) (TRide, error) {
	row := q.db.QueryRow(ctx, updateRideStatus, arg.RideID, arg.RideStatus)
	var i TRide
	err := row.Scan(
		&i.RideID,
		&i.RideRiderID,
		&i.RideDriverID,
		&i.RidePickupLat,
		&i.RidePickupLon,
		&i.RideDropoffLat,
		&i.RideDropoffLon,
		&i.RideStatus,
		&i.RidePrice,
		&i.RideCreatedAt,
		&i.RideUpdatedAt,
	)
	return i, err
}
