// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AccountRole string

const (
	AccountRoleRIDER  AccountRole = "RIDER"
	AccountRoleDRIVER AccountRole = "DRIVER"
	AccountRoleADMIN  AccountRole = "ADMIN"
)

func (e *AccountRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountRole(s)
	case string:
		*e = AccountRole(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountRole: %T", src)
	}
	return nil
}

type NullAccountRole struct {
	AccountRole AccountRole `json:"account_role"`
	Valid       bool        `json:"valid"` // Valid is true if AccountRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountRole) Scan(value interface{}) error {
	if value == nil {
		ns.AccountRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountRole), nil
}

type AccountStatus string

const (
	AccountStatusACTIVE    AccountStatus = "ACTIVE"
	AccountStatusSUSPENDED AccountStatus = "SUSPENDED"
	AccountStatusBANNED    AccountStatus = "BANNED"
)

func (e *AccountStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountStatus(s)
	case string:
		*e = AccountStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountStatus: %T", src)
	}
	return nil
}

type NullAccountStatus struct {
	AccountStatus AccountStatus `json:"account_status"`
	Valid         bool          `json:"valid"` // Valid is true if AccountStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AccountStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountStatus), nil
}

type TOutboxEvent struct {
	EventID            pgtype.UUID        `json:"event_id"`
	EventAggregateID   string             `json:"event_aggregate_id"`
	EventAggregateType string             `json:"event_aggregate_type"`
	EventType          string             `json:"event_type"`
	EventPayload       []byte             `json:"event_payload"`
	EventStatus        string             `json:"event_status"`
	EventCreatedAt     pgtype.Timestamptz `json:"event_created_at"`
	EventUpdatedAt     pgtype.Timestamptz `json:"event_updated_at"`
	EventPublishedAt   pgtype.Timestamptz `json:"event_published_at"`
}

type TUser struct {
	UserID          pgtype.UUID        `json:"user_id"`
	UserEmail       pgtype.Text        `json:"user_email"`
	UserPhone       pgtype.Text        `json:"user_phone"`
	UserDisplayName pgtype.Text        `json:"user_display_name"`
	UserAvatarUrl   pgtype.Text        `json:"user_avatar_url"`
	UserRole        AccountRole        `json:"user_role"`
	UserStatus      AccountStatus      `json:"user_status"`
	UserCreatedAt   pgtype.Timestamptz `json:"user_created_at"`
	UserUpdatedAt   pgtype.Timestamptz `json:"user_updated_at"`
}
