// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (TOutboxEvent, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (TUser, error)
	GetPendingOutboxEvents(ctx context.Context, limit int32) ([]TOutboxEvent, error)
	GetUserByID(ctx context.Context, userID pgtype.UUID) (TUser, error)
	MarkOutboxEventAsFailed(ctx context.Context, eventID pgtype.UUID) error
	MarkOutboxEventAsPublished(ctx context.Context, eventID pgtype.UUID) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (TUser, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (TUser, error)
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (TUser, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (TUser, error)
}

var _ Querier = (*Queries)(nil)
