// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO t_users (
    user_id,
    user_email,
    user_phone,
    user_display_name,
    user_avatar_url,
    user_role,
    user_status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING user_id, user_email, user_phone, user_display_name, user_avatar_url, user_role, user_status, user_created_at, user_updated_at
`

type CreateUserParams struct {
	UserID          pgtype.UUID   `json:"user_id"`
	UserEmail       pgtype.Text   `json:"user_email"`
	UserPhone       pgtype.Text   `json:"user_phone"`
	UserDisplayName pgtype.Text   `json:"user_display_name"`
	UserAvatarUrl   pgtype.Text   `json:"user_avatar_url"`
	UserRole        AccountRole   `json:"user_role"`
	UserStatus      AccountStatus `json:"user_status"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (TUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.UserID,
		arg.UserEmail,
		arg.UserPhone,
		arg.UserDisplayName,
		arg.UserAvatarUrl,
		arg.UserRole,
		arg.UserStatus,
	)
	var i TUser
	err := row.Scan(
		&i.UserID,
		&i.UserEmail,
		&i.UserPhone,
		&i.UserDisplayName,
		&i.UserAvatarUrl,
		&i.UserRole,
		&i.UserStatus,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, user_email, user_phone, user_display_name, user_avatar_url, user_role, user_status, user_created_at, user_updated_at FROM t_users
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, userID pgtype.UUID) (TUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i TUser
	err := row.Scan(
		&i.UserID,
		&i.UserEmail,
		&i.UserPhone,
		&i.UserDisplayName,
		&i.UserAvatarUrl,
		&i.UserRole,
		&i.UserStatus,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE t_users
SET user_display_name = COALESCE($2, user_display_name),
    user_avatar_url = COALESCE($3, user_avatar_url),
    user_updated_at = NOW()
WHERE user_id = $1
RETURNING user_id, user_email, user_phone, user_display_name, user_avatar_url, user_role, user_status, user_created_at, user_updated_at
`

type UpdateUserProfileParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	UserDisplayName pgtype.Text `json:"user_display_name"`
	UserAvatarUrl   pgtype.Text `json:"user_avatar_url"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (TUser, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.UserID, arg.UserDisplayName, arg.UserAvatarUrl)
	var i TUser
	err := row.Scan(
		&i.UserID,
		&i.UserEmail,
		&i.UserPhone,
		&i.UserDisplayName,
		&i.UserAvatarUrl,
		&i.UserRole,
		&i.UserStatus,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE t_users
SET user_role = $2, user_updated_at = NOW()
WHERE user_id = $1
RETURNING user_id, user_email, user_phone, user_display_name, user_avatar_url, user_role, user_status, user_created_at, user_updated_at
`

type UpdateUserRoleParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	UserRole AccountRole `json:"user_role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (TUser, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.UserID, arg.UserRole)
	var i TUser
	err := row.Scan(
		&i.UserID,
		&i.UserEmail,
		&i.UserPhone,
		&i.UserDisplayName,
		&i.UserAvatarUrl,
		&i.UserRole,
		&i.UserStatus,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE t_users
SET user_status = $2, user_updated_at = NOW()
WHERE user_id = $1
RETURNING user_id, user_email, user_phone, user_display_name, user_avatar_url, user_role, user_status, user_created_at, user_updated_at
`

type UpdateUserStatusParams struct {
	UserID     pgtype.UUID   `json:"user_id"`
	UserStatus AccountStatus `json:"user_status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (TUser, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.UserID, arg.UserStatus)
	var i TUser
	err := row.Scan(
		&i.UserID,
		&i.UserEmail,
		&i.UserPhone,
		&i.UserDisplayName,
		&i.UserAvatarUrl,
		&i.UserRole,
		&i.UserStatus,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO t_users (
    user_id,
    user_email,
    user_phone,
    user_role
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (user_id) DO UPDATE
SET user_email = EXCLUDED.user_email,
    user_phone = EXCLUDED.user_phone,
    user_updated_at = NOW()
RETURNING user_id, user_email, user_phone, user_display_name, user_avatar_url, user_role, user_status, user_created_at, user_updated_at
`

type UpsertUserParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	UserEmail pgtype.Text `json:"user_email"`
	UserPhone pgtype.Text `json:"user_phone"`
	UserRole  AccountRole `json:"user_role"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (TUser, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.UserID,
		arg.UserEmail,
		arg.UserPhone,
		arg.UserRole,
	)
	var i TUser
	err := row.Scan(
		&i.UserID,
		&i.UserEmail,
		&i.UserPhone,
		&i.UserDisplayName,
		&i.UserAvatarUrl,
		&i.UserRole,
		&i.UserStatus,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}
