server:
  port: "8114"
  mode: "development"

database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "mysecretpassword"
  dbname: "echoride_db"
  type: "postgres"

kafka:
  brokers:
    - "localhost:9092"
  topic: "auth.events"
  user_topic: "user.events"

jaeger:
 service_host: "localhost"
 service_port: 4317

jwt:
    secret: "mysecretkey"
    access_token_ttl_min: 15
    refresh_token_ttl_hours: 720

redis:
    addr: "localhost:6379"
    password: ""
    db: 0

user_service:
    grpc_addr: "localhost:9115"