server:
  port: "8114"
  mode: "development"

database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "mysecretpassword"
  dbname: "echoride_db"
  type: "postgres"

kafka:
  brokers:
    - "localhost:9092"
  topic: "ride.events"

jaeger:
 service_host: "localhost"
 service_port: 4317

jwt:
    secret: "mysecretkey"
    expiration_time: 3600 # 1 hour in seconds