// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: location/v1/location.proto

package generated

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindNearestDriversRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideId        string                 `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	PickupLat     float64                `protobuf:"fixed64,2,opt,name=pickup_lat,json=pickupLat,proto3" json:"pickup_lat,omitempty"`
	PickupLng     float64                `protobuf:"fixed64,3,opt,name=pickup_lng,json=pickupLng,proto3" json:"pickup_lng,omitempty"`
	RadiusKm      float64                `protobuf:"fixed64,4,opt,name=radius_km,json=radiusKm,proto3" json:"radius_km,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindNearestDriversRequest) Reset() {
	*x = FindNearestDriversRequest{}
	mi := &file_location_v1_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindNearestDriversRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNearestDriversRequest) ProtoMessage() {}

func (x *FindNearestDriversRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNearestDriversRequest.ProtoReflect.Descriptor instead.
func (*FindNearestDriversRequest) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{0}
}

func (x *FindNearestDriversRequest) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *FindNearestDriversRequest) GetPickupLat() float64 {
	if x != nil {
		return x.PickupLat
	}
	return 0
}

func (x *FindNearestDriversRequest) GetPickupLng() float64 {
	if x != nil {
		return x.PickupLng
	}
	return 0
}

func (x *FindNearestDriversRequest) GetRadiusKm() float64 {
	if x != nil {
		return x.RadiusKm
	}
	return 0
}

func (x *FindNearestDriversRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type DriverEtaInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	DistanceKm    float64                `protobuf:"fixed64,2,opt,name=distance_km,json=distanceKm,proto3" json:"distance_km,omitempty"`
	Lat           float64                `protobuf:"fixed64,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,4,opt,name=lng,proto3" json:"lng,omitempty"`
	EtaSeconds    int32                  `protobuf:"varint,5,opt,name=eta_seconds,json=etaSeconds,proto3" json:"eta_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverEtaInfo) Reset() {
	*x = DriverEtaInfo{}
	mi := &file_location_v1_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverEtaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverEtaInfo) ProtoMessage() {}

func (x *DriverEtaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverEtaInfo.ProtoReflect.Descriptor instead.
func (*DriverEtaInfo) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{1}
}

func (x *DriverEtaInfo) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *DriverEtaInfo) GetDistanceKm() float64 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

func (x *DriverEtaInfo) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *DriverEtaInfo) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *DriverEtaInfo) GetEtaSeconds() int32 {
	if x != nil {
		return x.EtaSeconds
	}
	return 0
}

type FindNearestDriversResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drivers       []*DriverEtaInfo       `protobuf:"bytes,1,rep,name=drivers,proto3" json:"drivers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindNearestDriversResponse) Reset() {
	*x = FindNearestDriversResponse{}
	mi := &file_location_v1_location_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindNearestDriversResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNearestDriversResponse) ProtoMessage() {}

func (x *FindNearestDriversResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNearestDriversResponse.ProtoReflect.Descriptor instead.
func (*FindNearestDriversResponse) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{2}
}

func (x *FindNearestDriversResponse) GetDrivers() []*DriverEtaInfo {
	if x != nil {
		return x.Drivers
	}
	return nil
}

var File_location_v1_location_proto protoreflect.FileDescriptor

const file_location_v1_location_proto_rawDesc = "" +
	"\n" +
	"\x1alocation/v1/location.proto\x12\vlocation.v1\"\xa5\x01\n" +
	"\x19FindNearestDriversRequest\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\x12\x1d\n" +
	"\n" +
	"pickup_lat\x18\x02 \x01(\x01R\tpickupLat\x12\x1d\n" +
	"\n" +
	"pickup_lng\x18\x03 \x01(\x01R\tpickupLng\x12\x1b\n" +
	"\tradius_km\x18\x04 \x01(\x01R\bradiusKm\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"\x92\x01\n" +
	"\rDriverEtaInfo\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x1f\n" +
	"\vdistance_km\x18\x02 \x01(\x01R\n" +
	"distanceKm\x12\x10\n" +
	"\x03lat\x18\x03 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x04 \x01(\x01R\x03lng\x12\x1f\n" +
	"\veta_seconds\x18\x05 \x01(\x05R\n" +
	"etaSeconds\"R\n" +
	"\x1aFindNearestDriversResponse\x124\n" +
	"\adrivers\x18\x01 \x03(\v2\x1a.location.v1.DriverEtaInfoR\adrivers2x\n" +
	"\x0fLocationService\x12e\n" +
	"\x12FindNearestDrivers\x12&.location.v1.FindNearestDriversRequest\x1a'.location.v1.FindNearestDriversResponseB:Z8Go-EchoRide/services/location-service/pkg/grpc/generatedb\x06proto3"

var (
	file_location_v1_location_proto_rawDescOnce sync.Once
	file_location_v1_location_proto_rawDescData []byte
)

func file_location_v1_location_proto_rawDescGZIP() []byte {
	file_location_v1_location_proto_rawDescOnce.Do(func() {
		file_location_v1_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_location_v1_location_proto_rawDesc), len(file_location_v1_location_proto_rawDesc)))
	})
	return file_location_v1_location_proto_rawDescData
}

var file_location_v1_location_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_location_v1_location_proto_goTypes = []any{
	(*FindNearestDriversRequest)(nil),  // 0: location.v1.FindNearestDriversRequest
	(*DriverEtaInfo)(nil),              // 1: location.v1.DriverEtaInfo
	(*FindNearestDriversResponse)(nil), // 2: location.v1.FindNearestDriversResponse
}
var file_location_v1_location_proto_depIdxs = []int32{
	1, // 0: location.v1.FindNearestDriversResponse.drivers:type_name -> location.v1.DriverEtaInfo
	0, // 1: location.v1.LocationService.FindNearestDrivers:input_type -> location.v1.FindNearestDriversRequest
	2, // 2: location.v1.LocationService.FindNearestDrivers:output_type -> location.v1.FindNearestDriversResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_location_v1_location_proto_init() }
func file_location_v1_location_proto_init() {
	if File_location_v1_location_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_location_v1_location_proto_rawDesc), len(file_location_v1_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_location_v1_location_proto_goTypes,
		DependencyIndexes: file_location_v1_location_proto_depIdxs,
		MessageInfos:      file_location_v1_location_proto_msgTypes,
	}.Build()
	File_location_v1_location_proto = out.File
	file_location_v1_location_proto_goTypes = nil
	file_location_v1_location_proto_depIdxs = nil
}
