server:
  port: "8115"
  mode: "development"

grpc:
  port: "9115"

database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "mysecretpassword"
  dbname: "echoride_db"
  type: "postgres"

kafka:
  brokers:
    - "localhost:9092"
  topic: "user.events"
  identity_topic: "auth.events"

jaeger:
 service_host: "localhost"
 service_port: 4317
