// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TIdentity struct {
	IdentityID           pgtype.UUID        `json:"identity_id"`
	IdentityEmail        string             `json:"identity_email"`
	IdentityPhone        string             `json:"identity_phone"`
	IdentityPasswordHash string             `json:"identity_password_hash"`
	IdentityCreatedAt    pgtype.Timestamptz `json:"identity_created_at"`
	IdentityUpdatedAt    pgtype.Timestamptz `json:"identity_updated_at"`
}

type TOutboxEvent struct {
	EventID            pgtype.UUID        `json:"event_id"`
	EventAggregateID   string             `json:"event_aggregate_id"`
	EventAggregateType string             `json:"event_aggregate_type"`
	EventType          string             `json:"event_type"`
	EventPayload       []byte             `json:"event_payload"`
	EventStatus        string             `json:"event_status"`
	EventCreatedAt     pgtype.Timestamptz `json:"event_created_at"`
	EventUpdatedAt     pgtype.Timestamptz `json:"event_updated_at"`
	EventPublishedAt   pgtype.Timestamptz `json:"event_published_at"`
}

type TRefreshToken struct {
	RefreshTokenID         pgtype.UUID        `json:"refresh_token_id"`
	RefreshTokenIdentityID pgtype.UUID        `json:"refresh_token_identity_id"`
	RefreshTokenHash       string             `json:"refresh_token_hash"`
	RefreshTokenDeviceInfo pgtype.Text        `json:"refresh_token_device_info"`
	RefreshTokenIpAddress  pgtype.Text        `json:"refresh_token_ip_address"`
	RefreshTokenUserAgent  pgtype.Text        `json:"refresh_token_user_agent"`
	RefreshTokenExpiresAt  pgtype.Timestamptz `json:"refresh_token_expires_at"`
	RefreshTokenRevokedAt  pgtype.Timestamptz `json:"refresh_token_revoked_at"`
	RefreshTokenLastUsedAt pgtype.Timestamptz `json:"refresh_token_last_used_at"`
	RefreshTokenCreatedAt  pgtype.Timestamptz `json:"refresh_token_created_at"`
}
