// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO t_outbox_events (
    event_aggregate_type,
    event_aggregate_id,
    event_type,
    event_payload
) VALUES ($1, $2, $3, $4)
RETURNING event_id, event_aggregate_id, event_aggregate_type, event_type, event_payload, event_status, event_created_at, event_updated_at, event_published_at
`

type CreateOutboxEventParams struct {
	EventAggregateType string `json:"event_aggregate_type"`
	EventAggregateID   string `json:"event_aggregate_id"`
	EventType          string `json:"event_type"`
	EventPayload       []byte `json:"event_payload"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (TOutboxEvent, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent,
		arg.EventAggregateType,
		arg.EventAggregateID,
		arg.EventType,
		arg.EventPayload,
	)
	var i TOutboxEvent
	err := row.Scan(
		&i.EventID,
		&i.EventAggregateID,
		&i.EventAggregateType,
		&i.EventType,
		&i.EventPayload,
		&i.EventStatus,
		&i.EventCreatedAt,
		&i.EventUpdatedAt,
		&i.EventPublishedAt,
	)
	return i, err
}

const getPendingOutboxEvents = `-- name: GetPendingOutboxEvents :many
SELECT event_id, event_aggregate_id, event_aggregate_type, event_type, event_payload, event_status, event_created_at, event_updated_at, event_published_at FROM t_outbox_events
WHERE event_status = 'PENDING'
ORDER BY event_created_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) GetPendingOutboxEvents(ctx context.Context, limit int32) ([]TOutboxEvent, error) {
	rows, err := q.db.Query(ctx, getPendingOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TOutboxEvent
	for rows.Next() {
		var i TOutboxEvent
		if err := rows.Scan(
			&i.EventID,
			&i.EventAggregateID,
			&i.EventAggregateType,
			&i.EventType,
			&i.EventPayload,
			&i.EventStatus,
			&i.EventCreatedAt,
			&i.EventUpdatedAt,
			&i.EventPublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventAsFailed = `-- name: MarkOutboxEventAsFailed :exec
UPDATE t_outbox_events
SET event_status = 'FAILED', event_updated_at = NOW()
WHERE event_id = $1
`

func (q *Queries) MarkOutboxEventAsFailed(ctx context.Context, eventID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventAsFailed, eventID)
	return err
}

const markOutboxEventAsPublished = `-- name: MarkOutboxEventAsPublished :exec
UPDATE t_outbox_events
SET event_status = 'PUBLISHED', event_published_at = NOW(), event_updated_at = NOW()
WHERE event_id = $1
`

func (q *Queries) MarkOutboxEventAsPublished(ctx context.Context, eventID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventAsPublished, eventID)
	return err
}
