// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"
)

type Querier interface {
	CreateIdentity(ctx context.Context, arg CreateIdentityParams) (TIdentity, error)
	GetIdentityByEmail(ctx context.Context, identityEmail string) (TIdentity, error)
	GetIdentityByPhone(ctx context.Context, identityPhone string) (TIdentity, error)
	UpdateIdentityStatus(ctx context.Context, arg UpdateIdentityStatusParams) (TIdentity, error)
}

var _ Querier = (*Queries)(nil)
