// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO t_identities (
    identity_email,
    identity_phone,
    identity_password_hash,
    identity_role
) VALUES (
    $1, $2, $3, $4
)
RETURNING identity_id, identity_email, identity_phone, identity_password_hash, identity_role, identity_status, identity_created_at, identity_updated_at
`

type CreateIdentityParams struct {
	IdentityEmail        string      `json:"identity_email"`
	IdentityPhone        string      `json:"identity_phone"`
	IdentityPasswordHash string      `json:"identity_password_hash"`
	IdentityRole         AccountRole `json:"identity_role"`
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (TIdentity, error) {
	row := q.db.QueryRow(ctx, createIdentity,
		arg.IdentityEmail,
		arg.IdentityPhone,
		arg.IdentityPasswordHash,
		arg.IdentityRole,
	)
	var i TIdentity
	err := row.Scan(
		&i.IdentityID,
		&i.IdentityEmail,
		&i.IdentityPhone,
		&i.IdentityPasswordHash,
		&i.IdentityRole,
		&i.IdentityStatus,
		&i.IdentityCreatedAt,
		&i.IdentityUpdatedAt,
	)
	return i, err
}

const getIdentityByEmail = `-- name: GetIdentityByEmail :one
SELECT identity_id, identity_email, identity_phone, identity_password_hash, identity_role, identity_status, identity_created_at, identity_updated_at FROM t_identities
WHERE identity_email = $1
LIMIT 1
`

func (q *Queries) GetIdentityByEmail(ctx context.Context, identityEmail string) (TIdentity, error) {
	row := q.db.QueryRow(ctx, getIdentityByEmail, identityEmail)
	var i TIdentity
	err := row.Scan(
		&i.IdentityID,
		&i.IdentityEmail,
		&i.IdentityPhone,
		&i.IdentityPasswordHash,
		&i.IdentityRole,
		&i.IdentityStatus,
		&i.IdentityCreatedAt,
		&i.IdentityUpdatedAt,
	)
	return i, err
}

const getIdentityByPhone = `-- name: GetIdentityByPhone :one
SELECT identity_id, identity_email, identity_phone, identity_password_hash, identity_role, identity_status, identity_created_at, identity_updated_at FROM t_identities
WHERE identity_phone = $1
LIMIT 1
`

func (q *Queries) GetIdentityByPhone(ctx context.Context, identityPhone string) (TIdentity, error) {
	row := q.db.QueryRow(ctx, getIdentityByPhone, identityPhone)
	var i TIdentity
	err := row.Scan(
		&i.IdentityID,
		&i.IdentityEmail,
		&i.IdentityPhone,
		&i.IdentityPasswordHash,
		&i.IdentityRole,
		&i.IdentityStatus,
		&i.IdentityCreatedAt,
		&i.IdentityUpdatedAt,
	)
	return i, err
}

const updateIdentityStatus = `-- name: UpdateIdentityStatus :one
UPDATE t_identities
SET identity_status = $2, identity_updated_at = NOW()
WHERE identity_id = $1
RETURNING identity_id, identity_email, identity_phone, identity_password_hash, identity_role, identity_status, identity_created_at, identity_updated_at
`

type UpdateIdentityStatusParams struct {
	IdentityID     pgtype.UUID   `json:"identity_id"`
	IdentityStatus AccountStatus `json:"identity_status"`
}

func (q *Queries) UpdateIdentityStatus(ctx context.Context, arg UpdateIdentityStatusParams) (TIdentity, error) {
	row := q.db.QueryRow(ctx, updateIdentityStatus, arg.IdentityID, arg.IdentityStatus)
	var i TIdentity
	err := row.Scan(
		&i.IdentityID,
		&i.IdentityEmail,
		&i.IdentityPhone,
		&i.IdentityPasswordHash,
		&i.IdentityRole,
		&i.IdentityStatus,
		&i.IdentityCreatedAt,
		&i.IdentityUpdatedAt,
	)
	return i, err
}
