// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_token.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO t_refresh_tokens (
    refresh_token_identity_id,
    refresh_token_hash,
    refresh_token_device_info,
    refresh_token_ip_address,
    refresh_token_user_agent,
    refresh_token_expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING refresh_token_id, refresh_token_identity_id, refresh_token_hash, refresh_token_device_info, refresh_token_ip_address, refresh_token_user_agent, refresh_token_expires_at, refresh_token_revoked_at, refresh_token_last_used_at, refresh_token_created_at
`

type CreateRefreshTokenParams struct {
	RefreshTokenIdentityID pgtype.UUID        `json:"refresh_token_identity_id"`
	RefreshTokenHash       string             `json:"refresh_token_hash"`
	RefreshTokenDeviceInfo pgtype.Text        `json:"refresh_token_device_info"`
	RefreshTokenIpAddress  pgtype.Text        `json:"refresh_token_ip_address"`
	RefreshTokenUserAgent  pgtype.Text        `json:"refresh_token_user_agent"`
	RefreshTokenExpiresAt  pgtype.Timestamptz `json:"refresh_token_expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (TRefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.RefreshTokenIdentityID,
		arg.RefreshTokenHash,
		arg.RefreshTokenDeviceInfo,
		arg.RefreshTokenIpAddress,
		arg.RefreshTokenUserAgent,
		arg.RefreshTokenExpiresAt,
	)
	var i TRefreshToken
	err := row.Scan(
		&i.RefreshTokenID,
		&i.RefreshTokenIdentityID,
		&i.RefreshTokenHash,
		&i.RefreshTokenDeviceInfo,
		&i.RefreshTokenIpAddress,
		&i.RefreshTokenUserAgent,
		&i.RefreshTokenExpiresAt,
		&i.RefreshTokenRevokedAt,
		&i.RefreshTokenLastUsedAt,
		&i.RefreshTokenCreatedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT refresh_token_id, refresh_token_identity_id, refresh_token_hash, refresh_token_device_info, refresh_token_ip_address, refresh_token_user_agent, refresh_token_expires_at, refresh_token_revoked_at, refresh_token_last_used_at, refresh_token_created_at FROM t_refresh_tokens
WHERE refresh_token_hash = $1
LIMIT 1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, refreshTokenHash string) (TRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, refreshTokenHash)
	var i TRefreshToken
	err := row.Scan(
		&i.RefreshTokenID,
		&i.RefreshTokenIdentityID,
		&i.RefreshTokenHash,
		&i.RefreshTokenDeviceInfo,
		&i.RefreshTokenIpAddress,
		&i.RefreshTokenUserAgent,
		&i.RefreshTokenExpiresAt,
		&i.RefreshTokenRevokedAt,
		&i.RefreshTokenLastUsedAt,
		&i.RefreshTokenCreatedAt,
	)
	return i, err
}

const revokeAllRefreshTokensByIdentity = `-- name: RevokeAllRefreshTokensByIdentity :exec
UPDATE t_refresh_tokens
SET refresh_token_revoked_at = NOW()
WHERE refresh_token_identity_id = $1 AND refresh_token_revoked_at IS NULL
`

func (q *Queries) RevokeAllRefreshTokensByIdentity(ctx context.Context, refreshTokenIdentityID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllRefreshTokensByIdentity, refreshTokenIdentityID)
	return err
}

const revokeRefreshTokenByHash = `-- name: RevokeRefreshTokenByHash :exec
UPDATE t_refresh_tokens
SET refresh_token_revoked_at = NOW()
WHERE refresh_token_hash = $1 AND refresh_token_revoked_at IS NULL
`

func (q *Queries) RevokeRefreshTokenByHash(ctx context.Context, refreshTokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenByHash, refreshTokenHash)
	return err
}

const touchRefreshTokenLastUsed = `-- name: TouchRefreshTokenLastUsed :exec
UPDATE t_refresh_tokens
SET refresh_token_last_used_at = NOW()
WHERE refresh_token_hash = $1
`

func (q *Queries) TouchRefreshTokenLastUsed(ctx context.Context, refreshTokenHash string) error {
	_, err := q.db.Exec(ctx, touchRefreshTokenLastUsed, refreshTokenHash)
	return err
}
