server:
  port: "8113"
  mode: "development"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 1

kafka:
  brokers:
    - "localhost:9092"
  topic: "ride.events"
  group_id: "matching-service-group"

dependencies:
  location_grpc_url: "localhost:9082"

grpc:
  port: "9082"