apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: ride-service-route
spec:
  http:
    - name: preview-route
      match:
        paths:
          - "/ride/preview"
        methods: ["POST"]
      backends:
        - serviceName: ride-service
          servicePort: 8083