server:
  port: "8081"
  mode: "development"

database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "mysecretpassword"
  dbname: "echoride_db"
  type: "postgres"

kafka:
  brokers:
    - "localhost:9092"
  topic: "ride.events"

jaeger:
 service_host: "localhost"
 service_port: 4317